[project]
name = "understanding"
version = "0.1.0"
description = ""
readme = "README.md"
requires-python = ">=3.14"
dependencies = []

[dependency-groups]
dev = [
    "graphviz>=0.21",
    "ipympl>=0.9.8",
    "jupyterlab>=4.4.10",
    "mypy>=1.18.2",
    "numpy>=2.3.4",
    "pandas>=2.3.3",
]
